# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Mr01qt9u6xp5pAxRvd6CrVTECPaHYlB
"""

!pip install netron
!pip install onnx

import torch
from torchvision.models import resnet18
import netron

# Create an instance of the model
model = resnet18()

# Export the model to ONNX format
dummy_input = torch.randn(1, 3, 224, 224)
torch.onnx.export(model, dummy_input, "model.onnx")

# Launch Netron to visualize the model
netron.start("model.onnx")

# Download the model. 
# run on https://netron.app/

!pip install torchview

import torchvision
from torchview import draw_graph

model_graph = draw_graph(model, input_size=(1,3,224,224), expand_nested=True)
model_graph.visual_graph.render(format='pdf')